import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "react-i18next";
import SearchProperties from "../components/PropertySearch";
import PopularSection from "../components/PopularSection";
import RomisMessage from "../components/RomisMessage";
import BlogsSection from "../components/BolgsSection";
import RomisTvsection from "../components/RomisTvSection";
import PropCategorySection from "../components/PropCategorySection";
import CardSection from "../components/CardSection";
import Footer from "../components/Footer";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
    },
  };
}

export default function Home(props) {
  const { t } = useTranslation();

  return (
    <div className={styles.container}>
      <div className={styles.header}></div>
      {/* <h1>{t("home:welcome_msg")}</h1> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.video_con}>
          <video className={styles.video} loop muted autoPlay>
            <source src="vid1.mp4" type="video/mp4" />
            <source src="vid2.mp4" type="video/mp4" />
          </video>{" "}
        </div>
        <div className={styles.search_popular}>
          <SearchProperties />
          <PopularSection />
          <RomisMessage />
        </div>
        <BlogsSection />
        <RomisTvsection />
        <PropCategorySection />
        <CardSection />
        <Footer />
        <div className="h-screen bg-gray">s</div>
      </main>
      <footer className={styles.footer}>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          width={72}
          height={16}
          style={{ background: "white" }}
        />
      </footer>
    </div>
  );
}
